//Date Correction

UPDATE  XXBCM_ORDER_MGT t1
SET t1.ORDER_DATE = TO_DATE('DD-MON-YYYY');

// Remove "." in SUPPLIER NAME FIELD

Select RTRIM(t1.SUPPLIER_NAME,’.’) from XXBCM_ORDER_MGT t1

//

UPDATE  XXBCM_ORDER_MGT t2
SET t2.SUPP_CONTACT_NUMBER = REPLACE(t.SUPP_CONTACT_NUMBER, 'S' , '5');

UPDATE  XXBCM_ORDER_MGT t2
SET t2.SUPP_CONTACT_NUMBER = REPLACE(t.SUPP_CONTACT_NUMBER, 'o' , '0');

UPDATE  XXBCM_ORDER_MGT t2
SET t2.SUPP_CONTACT_NUMBER = REPLACE(t.SUPP_CONTACT_NUMBER, 'I' , '1')


// Convert to Numerical Value

UPDATE XXBCM_ORDER_MGT t3
SET t3.ORDER_LINE_AMOUNT = '100000'
WHERE t3.ORDER_LINE_AMOUNT ='10000o'

UPDATE XXBCM_ORDER_MGT t3
SET t3.ORDER_LINE_AMOUNT = '5000'
WHERE t3.ORDER_LINE_AMOUNT ='S,000'

UPDATE XXBCM_ORDER_MGT t3
SET t3.ORDER_LINE_AMOUNT = '1200'
WHERE t3.ORDER_LINE_AMOUNT ='I200'

UPDATE XXBCM_ORDER_MGT t3
SET t3.ORDER_LINE_AMOUNT = '30250'
WHERE t3.ORDER_LINE_AMOUNT ='3025o'

UPDATE XXBCM_ORDER_MGT t3
SET t3.ORDER_LINE_AMOUNT = '3450'
WHERE t3.ORDER_LINE_AMOUNT ='3,4S0'



UPDATE XXBCM_ORDER_MGT t4
SET t4.INVOICE_AMOUNT = '2500'
WHERE t4.INVOICE_AMOUNT  ='25oo'

UPDATE XXBCM_ORDER_MGT t4
SET t4.INVOICE_AMOUNT = '1200'
WHERE t4.INVOICE_AMOUNT  ='I200'

UPDATE XXBCM_ORDER_MGT t4
SET t4.INVOICE_AMOUNT = '5000'
WHERE t4.INVOICE_AMOUNT  ='S000'





