create PROCEDURE DATA_MIGRATION
IS
BEGIN 
insert into tbl_SUPPLIER
(SUPPL_NAME, SUPPL_ADDRESS, SUPPL_EMAIL)
Select Distinct SUPPLIER_NAME,SUPP_ADDRESS,SUPP_EMAIL
from XXBCM_ORDER_MGT;

insert into tbl_SUPPLIER_CONTACT
(SUPPL_NAME,SUPPL_CONTACT_NAME,SUPPL_CONTACT_NUMBER)
Select Distinct SUPPLIER_NAME,,SUPP_CONTACT_NAME,SUPP_CONTACT_NUMBER
from XXBCM_ORDER_MGT;

insert into tbl_ORDER_DETAILS
(ORDER_REF,ORDER_DATE,ORDER_TOTAL_AMOUNT,ORDER_DESCRIPTION,ORDER_LINE_AMOUNT)
Select Distinct ORDER_REF,ORDER_DATE,ORDER_TOTAL_AMOUNT,ORDER_DESCRIPTION,ORDER_LINE_AMOUNT
from XXBCM_ORDER_MGT;

insert into tbl_SUPPLIER_ORDER
(ORDER_REF, SUPPL_NAME,  ORDER_STATUS)
Select Distinct ORDER_REF,SUPPLIER_NAME,  ORDER_STATUS
from XXBCM_ORDER_MGT;

insert into tbl_INVOICE 
(INV_REF,INV_DATE,INV_HOLD_REASON,INV_AMOUNT,INV_DESCRIPTION) 
Select Distinct INVOICE_REFERENCE,INVOICE_DATE,INVOICE_HOLD_REASON,INVOICE_AMOUNT,INVOICE_DESCRIPTION
from XXBCM_ORDER_MGT;


insert into tbl_SUPPLIER_INVOICE (
INV_REF, ORDER_REF, INV_STATUS
Select Distinct INVOICE_REFERENCE,ORDER_REF,INVOICE_STATUS 
from XXBCM_ORDER_MGT;

end DATA_MIGRATION;


